name: basedocker-full

on:
  push:
    branches:
      - master
    paths:
      - "basedocker/full/*"
  pull_request:
    branches:
      - master
    paths:
      - "basedocker/full/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: buildx
        run: export DOCKER_CLI_EXPERIMENTAL=enabled && docker buildx create --use --name tars-builder && docker buildx inspect tars-builder --bootstrap && docker buildx ls
      - name: test buildx
        run: docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
      - name: docker login
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
      - name: docker build
        run: docker buildx build -t tarscloud/tars-env-test:latest --platform=linux/amd64,linux/arm64 -f basedocker/full/Dockerfile basedocker/full --push
