name: basedocker-full

on:
  push:
    branches:
      - arm 
    paths:
      - "basedocker/full/*"
  pull_request:
    branches:
      - arm
    paths:
      - "basedocker/full/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: buildx
        run: export DOCKER_CLI_EXPERIMENTAL=enabled && docker buildx create --use --name tars-builder && docker buildx inspect tars-builder --bootstrap && docker buildx ls
      - name: docker login
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
      - name: docker build
        run: docker buildx build -t tarscloud/tars-env-test --platform=linux/amd64,linux/arm64 -f basedocker/full/arm64.Dockerfile basedocker/full 
