name: basedocker-full

on:
  push:
    branches:
      - master
    paths:
      - "basedocker/full/*"
  pull_request:
    branches:
      - master
    paths:
      - "basedocker/full/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker build
        run: cd basedocker/full && ./build-docker.sh test
