name: framework

on:
  push:
    branches:
      - master
    paths:
      - "framework/**"
  pull_request:
    branches:
      - master
    paths:
      - "framework/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: buildx
        run: export DOCKER_CLI_EXPERIMENTAL=enabled && docker buildx create --use --name tars-builder && docker buildx inspect tars-builder --bootstrap && docker buildx ls
      - name: test buildx
        run: docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
      - name: Build framework image
        run: docker buildx build ./framework/ --file ./framework/Dockerfile --tag tarscloud/framework:latest --platform=linux/amd64,linux/arm64
