name: framework-dev

on:
  push:
    branches:
      - dev
    paths:
      - "framework/**"
      - ".github/workflows/framework-dev.yml"
  pull_request:
    branches:
      - dev
    paths:
      - "framework/**"
  schedule:
    - cron: 0 23 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build framework-dev image
        run: cd framework && ./build-docker.sh master master dev
