name: framework-dev

on:
  push:
    branches:
      - dev
    paths:
      - "framework/**"
  pull_request:
    branches:
      - dev
    paths:
      - "framework/**"
  schedule:
    - cron: 0 23 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: buildx
        run: export DOCKER_CLI_EXPERIMENTAL=enabled && docker buildx create --use --name tars-builder && docker buildx inspect tars-builder --bootstrap && docker buildx ls
      - name: test buildx
        run: docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
      - name: Build framework-dev image
        run: docker buildx build ./framework/ --file ./framework/Dockerfile --tag framework:dev-$(date +%s) --platform=linux/amd64,linux/arm64
