name: framework

on:
  push:
    branches:
      - master
    paths:
      - "framework/**"
  pull_request:
    branches:
      - master
    paths:
      - "framework/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build framework image
        run: cd framework && ./build-docker.sh latest latest latest 
