name: framework

on:
  push:
    branches:
      - master
    paths:
      - "framework/**"
      - ".github/workflows/framework.yml"
  pull_request:
    branches:
      - master
    paths:
      - "framework/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build framework image
        run: cd framework && ./build-docker.sh master master latest 
