name: tarsnode-cpp

on:
  push:
    branches:
      - master
    paths:
      - "basedocker/full/*"
      - "tarsnode/cpp/*"
      - ".github/workflows/tarsnode-cpp.yml"
  pull_request:
    branches:
      - master
    paths:
      - "tarsnode/cpp/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build
        run: cd tarsnode && ./build-docker.sh cpp
