name: tars

on:
  push:
    branches:
      - master
    paths:
      - "tars/**"
  pull_request:
    branches:
      - master
    paths:
      - "tars/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build tars image
        run: cd tars && ./build-docker.sh latest latest latest
